### ISSUE TITLE
java.lang.NoClassDefFoundError: org.junit.runner.Runner

### ISSUE THREAD

**Issue by atorras-scytl** [corretto/corretto-8#166]
### Describe the bug
We're facing a NoClassDefFoundError while executing a Maven compile-test-package cycle with the following java version (Windows 10):

> openjdk version "1.8.0_222"
> OpenJDK Runtime Environment Corretto-8.222.10.3 (build 1.8.0_222-b10)
> OpenJDK 64-Bit Server VM Corretto-8.222.10.3 (build 25.222-b10, mixed mode)

The same problem occurs with _nearly-the-same_ version of OpenJDK (downloaded from https://github.com/AdoptOpenJDK/openjdk8-upstream-binaries/releases/tag/jdk8u212-b03) :

> openjdk version "1.8.0_222"
> OpenJDK Runtime Environment (build 1.8.0_222-10)
> OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

Nevertheless, the same Maven cycle works correctly with an Oracle JDK 212.

Doing some tests, the jre\bin\server\jvm.dll copied from Oracle's JDK into Corretto solved the problem.

### To Reproduce
N/A

### Expected behavior
No Error/Exception should be thrown.

### Screenshots
N/A

### Platform information
    OS: Windows 10
    Version Corretto-8.222.10.3 (build 1.8.0_222-b10) (the complete output is above)

### Additional context
The highlighted output produced by Maven is the following:

...
[ERROR] XYZTest  Time elapsed: 0.094 s  <<< ERROR!
java.lang.NoClassDefFoundError: org.junit.runner.Runner
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:362)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project XYZ: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Git\XYZ\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project XYZ: There are test failures.

Please refer to C:\Git\XYZ\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to C:\Git\XYZ\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
        at org.apache.maven.plugin.surefire.SurefireHelper.throwException(SurefireHelper.java:289)
        at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:161)
        at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:364)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1041)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

**Comment by cliveverghese** [comment]
Hi @atorras-scytl,

Thank you for reporting the issue. We would like to look into this, could you provide us a Reproduction case for this issue?

**Comment by atorras-scytl** [comment]
Hi @cliveverghese,

I'm afraid I'm not able to provide it. Nevertheless I'll do some checks in my spare time.

**Comment by atorras-scytl** [comment]
Hi @cliveverghese,

We've been able to reproduce it again with a Ubuntu 18 LTS OpenJDK installation, so it's definitely not related to Corretto but OpenJDK, despite the underlying OS, so I think this issue could be closed.

Regards,

**Comment by atorras-scytl** [comment]
Hi,

After some tries, we've seen it's caused by Surefire-Junit-Jmockit integration. It's been solved by setting surefire to fork, with javaagent argument.
