### ISSUE TITLE
How can I update timezone data (tzdb.dat) ? 

### ISSUE THREAD

**Issue by jinho-actgames** [corretto/corretto-8#200]
Hi

I need update timezone data (tzdb.dat). And I tried with tzupdater.jar privieded by Oracle.
But it make below errors.

shell> java -jar tzupdater.jar -V
tzupdater version 2.3.0-b01
JRE tzdata version: tzdata2019c
java.lang.NullPointerException
Exception in thread "main" com.sun.tools.tzupdater.TzRuntimeException: java.lang.NullPointerException
        at com.sun.tools.tzupdater.TimezoneUpdater.main(TimezoneUpdater.java:705)
Caused by: java.lang.NullPointerException
        at com.sun.tools.tzupdater.TimezoneUpdater.run(TimezoneUpdater.java:237)
        at com.sun.tools.tzupdater.TimezoneUpdater.main(TimezoneUpdater.java:686)

Is there alternative way to update timezone data ? 

Thanks.

**Comment by cliveverghese** [comment]
Hi @jinho-actgames , 

Corretto users have had success using the open source [ZIUpdater](https://www.azul.com/products/open-source-tools/ziupdater-time-zone-tool/). 

Please do let us know if this works for you.
