### ISSUE TITLE
ClassLoader.loadLibrary NullPointerException

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [corretto/corretto-8#212]
### Describe the bug
Corretto release 8.242.07.1 introduced a NullPointerException to ClassLoader.loadLibrary in certain circumstances. I confirmed 8.232.09.1 does not experience this bug.  

### To Reproduce
Reproducing this is a bit complicated as I'm running a third party program ([TeamCity](https://www.jetbrains.com/teamcity/download/#section=section-get))

You can use their docker container to reproduce the bug though
 - change the [version](https://github.com/JetBrains/teamcity-docker-server/blob/master/ubuntu/Dockerfile#L14) to https://corretto.aws/downloads/resources/8.242.07.1/amazon-corretto-8.242.07.1-linux-x64.tar.gz
- 
- hit the server on http://localhost:8111/
- exception is logged to /opt/teamcity/logs/catalina.out

I can explain more if there is interest.  

### Expected behavior
native library to be loaded without NPE

### Stacktrace

```
java.lang.ExceptionInInitializerError
    at sun.nio.ch.SocketChannelImpl$DefaultOptionsHolder.defaultOptions(SocketChannelImpl.java:239)
    at sun.nio.ch.SocketChannelImpl$DefaultOptionsHolder.<clinit>(SocketChannelImpl.java:226)
    at sun.nio.ch.SocketChannelImpl.supportedOptions(SocketChannelImpl.java:248)
    at sun.nio.ch.SocketChannelImpl.setOption(SocketChannelImpl.java:166)
    at sun.nio.ch.SocketAdaptor.setIntOption(SocketAdaptor.java:294)
    at sun.nio.ch.SocketAdaptor.setReceiveBufferSize(SocketAdaptor.java:375)
    at org.apache.tomcat.util.net.SocketProperties.setProperties(SocketProperties.java:183)
    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:400)
    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:502)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1847)
    at java.lang.Runtime.loadLibrary0(Runtime.java:871)
    at java.lang.System.loadLibrary(System.java:1124)
    at sun.net.ExtendedOptionsImpl.lambda$static$0(ExtendedOptionsImpl.java:48)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.net.ExtendedOptionsImpl.<clinit>(ExtendedOptionsImpl.java:47)
    ... 10 more

```

### Platform information
Amazon Linux 1

openjdk version "1.8.0_242"
OpenJDK Runtime Environment Corretto-8.242.08.1 (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM Corretto-8.242.08.1 (build 25.242-b08, mixed mode)

 
### Additional context

The bug is in src/jdk/src/share/classes/java/lang/ClassLoader.java

https://github.com/corretto/corretto-8/compare/8.232.09.1...8.242.07.1#diff-09a3e014719032eb85f90d0eea6b1d5f

and was introduced by this commit https://github.com/openjdk/jdk/commit/4b7bbaf5b001c17e3bcd8d8ec7e4cb2d66e795e5

Where a NPE can be triggered in `ClassLoader.loadLibrary(ClassLoader.java:1847)` if `usr_paths` has not been initialized by previously calling `ClassLoader.initLibraryPaths`

This may have been fixed by https://github.com/openjdk/jdk/commit/c639682887a83b98469ad1378de6a0db84b87c9f

**Comment by chris-smith-zocdoc** [comment]
I've also sent this to the 8u mailing list https://mail.openjdk.java.net/pipermail/jdk8u-dev/2020-January/011026.html

**Comment by simonis** [comment]
Hi Chris,
thanks for your report. As you've correctly noticed, this seems to be an upstream problem.
We'll definitely look at this and try to fix it as quick as possible in both, Corretto and the OpenJDK.
Best regards,
Volker

**Comment by alvdavi** [comment]
Hi,

This should've been fixed by:
https://bugs.openjdk.java.net/browse/JDK-8240521
