### ISSUE TITLE
Issue with corretto 8 jdk (updated from oracle JDK) 

### ISSUE THREAD

**Issue by Kaushal38** [corretto/corretto-8#216]
java.lang.NullPointerException
at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
at sun.font.SunFontManager$2.run(SunFontManager.java:431)
at java.security.AccessController.doPrivileged(Native Method)
at sun.font.SunFontManager.(SunFontManager.java:376)
at sun.awt.FcFontManager.(FcFontManager.java:35)
at sun.awt.X11FontManager.(X11FontManager.java:57)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at java.lang.Class.newInstance(Class.java:442)
at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
at java.security.AccessController.doPrivileged(Native Method)
at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
at java.awt.Font.getFont2D(Font.java:491)
at java.awt.Font.canDisplayUpTo(Font.java:2064)
at java.awt.font.TextLayout.singleFont(TextLayout.java:470)
at java.awt.font.TextLayout.(TextLayout.java:531)
at org.apache.poi.ss.util.SheetUtil.getColumnWidth(SheetUtil.java:208)
at org.apache.poi.hssf.usermodel.HSSFSheet.autoSizeColumn(HSSFSheet.java:1954)
at org.apache.poi.hssf.usermodel.HSSFSheet.autoSizeColumn(HSSFSheet.java:1937)
at com.mettl.excelGenerator.writers.TestSummarySheetWriter.createHeaders(TestSummarySheetWriter.java:289)

**Comment by TianminShi** [comment]
Hi, Are you getting this error message after witching from Oracle JDK to Corretto JDK ? 
could you please provide the version of Oracle JDK which was used before and the version of  Corretto JDK which throw this error message?
just FYI : you can get JDK version by running the following command
java -version

**Comment by alvdavi** [comment]
Hi,

This seems to be the same issue as #64 

Could you please check you have `fontconfig` installed in the system

**Comment by davecurrie** [comment]
@Kaushal38 can you please confirm this happens with fontconfig installed on your system?
