### ISSUE TITLE
8.252.09.1+ error with Payara 5.201 sun.security.ssl.Handshaker.setApplicationProtocols

### ISSUE THREAD

**Issue by rockn4** [corretto/corretto-8#233]
Noticed this while installing my app using the latest Corretto 8 build. Issue is seen in 8.252.09.1 and 8.252.09.2. Was able to roll back to 8.242.08.1 which works. SSL Socket issue seems to occur when initiating a connection to a database.

StandardWrapperValve[RServlet]: Servlet.service() for servlet RServlet threw exception
java.lang.NoSuchMethodError: sun.security.ssl.Handshaker.setApplicationProtocols([Ljava/lang/String;)V
	at sun.security.ssl.SSLSocketImpl.initHandshaker(SSLSocketImpl.java:1350)
	at sun.security.ssl.SSLSocketImpl.doneConnect(SSLSocketImpl.java:708)
	at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:583)
	at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:110)
	at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:1368)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:1058)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:833)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:716)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:841)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)

**Comment by rockn4** [comment]
Maybe I should clarify I'm using Windows and connecting to a Microsoft SQL Server database.

**Comment by davecurrie** [comment]
Hi @rockn4 

It looks like the 8u252 version of sun.security.ssl.SSLSocketImpl.initHandshaker is trying to use an older version of sun.security.ssl.Handshaker. Since both these classes are shipped in the same jar (jre/lib/jsse.jar), this is very strange. I've just confirmed that the 8u252 versions of both classes are in the jar that we have shipped.

Can you check your classpath to see if there is another version of jsse.jar being loaded at some point? Is your JAVA_HOME and so on set to the right directory? What process did you go through to upgrade?

**Comment by rockn4** [comment]
@davecurrie 
Thanks for looking into this so quickly! This was a fresh Windows Server 2019 install with 8.252.09.02 being the first/only installation of java being installed on this server. I used the Win x64 JDK MSI installers for all Corretto 8 builds that I installed/uninstalled. I noticed the issue right away and traced it back by uninstalling 8.252.09.02, installing 8.252.09.01 (noticing the same behavior), and then uninstalling 8.252.09.01, installing 8.242.08.1 for the 'fix'.

I also confirmed that going back to a 8u252 build again brought the issue back.

The classpath and java_home were standard default settings that are set with the MSI installer.

**Comment by davecurrie** [comment]
This seems to be a bug in Payara accessing private APIs in the JDK. See https://github.com/payara/Payara/issues/4625 for more details and a potential workaround. They also say that this failure is gone in JDK 9+. If you can run on Corretto 11, I would recommend it. Closing for now, please re-open if this doesn't address the issue.
