### ISSUE TITLE
Error starting connector: java.net.SocketException: java.security.NoSuchAlgorithmException on migrating from Oracle 8 to Corretto 8

### ISSUE THREAD

**Issue by Yoshitha24** [corretto/corretto-8#273]
Hi,

We are migrating from Oracle JDK 8 to Corretto JDK 8.We use JBoss 4.2.1GA as our application server on Linux 2.6.32-573.38.1.el6.x86_64,amd64 operating system. On running our services we are facing with the below mentioned exception.

ERROR [Connector] Error starting connector.
java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
	at javax.net.ssl.DefaultSSLServerSocketFactory.throwException(SSLServerSocketFactory.java:160)
	at javax.net.ssl.DefaultSSLServerSocketFactory.createServerSocket(SSLServerSocketFactory.java:188)
	at org.jboss.remoting.transport.sslsocket.SSLSocketServerInvoker.createServerSocket(SSLSocketServerInvoker.java:58)
	at org.jboss.remoting.transport.socket.SocketServerInvoker.start(SocketServerInvoker.java:193)
	at org.jboss.remoting.transport.Connector.start(Connector.java:322)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:155)
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:94)
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:86)
	at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:264)
	at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:659)
	at org.jboss.system.ServiceController$ServiceProxy.invoke(ServiceController.java:995)
	at com.sun.proxy.$Proxy0.start(Unknown Source)
	at org.jboss.system.ServiceController.start(ServiceController.java:417)
	at org.jboss.system.ServiceController.start(ServiceController.java:435)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:155)
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:94)
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:86)
	at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:264)
	at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:659)
	at org.jboss.mx.util.MBeanProxyExt.invoke(MBeanProxyExt.java:210)
	at com.sun.proxy.$Proxy4.start(Unknown Source)
	at org.jboss.deployment.SARDeployer.start(SARDeployer.java:302)
	at org.jboss.deployment.MainDeployer.start(MainDeployer.java:1025)
	at org.jboss.deployment.MainDeployer.deploy(MainDeployer.java:819)
	at org.jboss.deployment.MainDeployer.deploy(MainDeployer.java:782)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:155)
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:94)
	at org.jboss.mx.interceptor.AbstractInterceptor.invoke(AbstractInterceptor.java:133)
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:88)
	at org.jboss.mx.interceptor.ModelMBeanOperationInterceptor.invoke(ModelMBeanOperationInterceptor.java:142)
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:88)
	at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:264)
	at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:659)
	at org.jboss.mx.util.MBeanProxyExt.invoke(MBeanProxyExt.java:210)
	at com.sun.proxy.$Proxy9.deploy(Unknown Source)
	at org.jboss.deployment.scanner.URLDeploymentScanner.deploy(URLDeploymentScanner.java:421)
	at org.jboss.deployment.scanner.URLDeploymentScanner.scan(URLDeploymentScanner.java:634)
	at org.jboss.deployment.scanner.AbstractDeploymentScanner$ScannerThread.doScan(AbstractDeploymentScanner.java:263)
	at org.jboss.deployment.scanner.AbstractDeploymentScanner.startService(AbstractDeploymentScanner.java:336)
	at org.jboss.system.ServiceMBeanSupport.jbossInternalStart(ServiceMBeanSupport.java:289)
	at org.jboss.system.ServiceMBeanSupport.jbossInternalLifecycle(ServiceMBeanSupport.java:245)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:155)
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:94)
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:86)
	at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:264)
	at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:659)
	at org.jboss.system.ServiceController$ServiceProxy.invoke(ServiceController.java:978)
	at com.sun.proxy.$Proxy0.start(Unknown Source)
	at org.jboss.system.ServiceController.start(ServiceController.java:417)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:155)
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:94)
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:86)
	at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:264)
	at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:659)
	at org.jboss.mx.util.MBeanProxyExt.invoke(MBeanProxyExt.java:210)
	at com.sun.proxy.$Proxy4.start(Unknown Source)
	at org.jboss.deployment.SARDeployer.start(SARDeployer.java:302)
	at org.jboss.deployment.MainDeployer.start(MainDeployer.java:1025)
	at org.jboss.deployment.MainDeployer.deploy(MainDeployer.java:819)
	at org.jboss.deployment.MainDeployer.deploy(MainDeployer.java:782)
	at org.jboss.deployment.MainDeployer.deploy(MainDeployer.java:766)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:155)
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:94)
	at org.jboss.mx.interceptor.AbstractInterceptor.invoke(AbstractInterceptor.java:133)
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:88)
	at org.jboss.mx.interceptor.ModelMBeanOperationInterceptor.invoke(ModelMBeanOperationInterceptor.java:142)
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:88)
	at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:264)
	at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:659)
	at org.jboss.mx.util.MBeanProxyExt.invoke(MBeanProxyExt.java:210)
	at com.sun.proxy.$Proxy5.deploy(Unknown Source)
	at org.jboss.system.server.ServerImpl.doStart(ServerImpl.java:482)
	at org.jboss.system.server.ServerImpl.start(ServerImpl.java:362)
	at org.jboss.Main.boot(Main.java:200)
	at org.jboss.Main$1.run(Main.java:508)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
	at java.security.Provider$Service.newInstance(Provider.java:1617)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
	at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
	at javax.net.ssl.SSLServerSocketFactory.getDefault(SSLServerSocketFactory.java:113)
	at org.jboss.remoting.transport.sslsocket.SSLSocketServerInvoker.getDefaultServerSocketFactory(SSLSocketServerInvoker.java:53)
	at org.jboss.remoting.ServerInvoker.createServerSocketFactory(ServerInvoker.java:1209)
	at org.jboss.remoting.ServerInvoker.setup(ServerInvoker.java:1074)
	at org.jboss.remoting.transport.socket.SocketServerInvoker.setup(SocketServerInvoker.java:157)
	at org.jboss.remoting.ServerInvoker.create(ServerInvoker.java:810)
	at org.jboss.remoting.transport.Connector.init(Connector.java:430)
	at org.jboss.remoting.transport.Connector.create(Connector.java:782)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:155)
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:94)
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:86)
	at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:264)
	at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:659)
	at org.jboss.system.ServiceController$ServiceProxy.invoke(ServiceController.java:995)
	at com.sun.proxy.$Proxy0.create(Unknown Source)
	at org.jboss.system.ServiceController.create(ServiceController.java:330)
	at org.jboss.system.ServiceController.create(ServiceController.java:273)
	at org.jboss.system.ServiceController.create(ServiceController.java:349)
	at org.jboss.system.ServiceController.create(ServiceController.java:273)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:155)
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:94)
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:86)
	at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:264)
	at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:659)
	at org.jboss.mx.util.MBeanProxyExt.invoke(MBeanProxyExt.java:210)
	at com.sun.proxy.$Proxy4.create(Unknown Source)
	at org.jboss.deployment.SARDeployer.create(SARDeployer.java:258)
	at org.jboss.deployment.MainDeployer.create(MainDeployer.java:969)
	at org.jboss.deployment.MainDeployer.deploy(MainDeployer.java:818)
	... 66 more
Caused by: java.security.KeyStoreException: problem accessing trust store
	at sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:75)
	at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:250)
	at sun.security.ssl.SSLContextImpl$DefaultManagersHolder.getTrustManagers(SSLContextImpl.java:882)
	at sun.security.ssl.SSLContextImpl$DefaultManagersHolder.<clinit>(SSLContextImpl.java:854)
	at sun.security.ssl.SSLContextImpl$DefaultSSLContext.<init>(SSLContextImpl.java:1027)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.security.Provider$Service.newInstance(Provider.java:1595)
	... 106 more
Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:792)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:57)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:71)
	at java.security.KeyStore.load(KeyStore.jav
a:1445)
	at sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:367)
	at sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:315)
	at sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:59)
	at sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:51)
	... 115 more
Caused by: java.security.UnrecoverableKeyException: Password verification failed
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:790)
	... 123 more

Please find the attached error.log for more details.
[error.log](https://github.com/corretto/corretto-8/files/5498751/error.log)

Does anyone know why this error keeps showing up and ways to resolve it? Does this have anything to do with moving to Amazon Corretto Crypto Provider?

**Comment by lutkerd** [comment]
Hi, can you share your JVM parameters? Where there any changes made while migrating the Corretto? If there is any sensitive information or password, please redact it. The inner most exceptions make me think it might just be your start up parameters for the keystore location or keystore password.

Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
Caused by: java.security.UnrecoverableKeyException: Password verification failed

**Comment by Yoshitha24** [comment]
We have not changed any JVM parameters while migrating to Corretto. The only change we did is to use icedtea instead of javaws.

 _ln -s /usr/lib/jvm/${java_name}/bin/java    /usr/bin/java
 ln -s /usr/lib/jvm/${java_name}/bin/javac   /usr/bin/javac
	ln -s /usr/lib/jvm/${java_name}/bin/keytool /usr/bin/keytool
	ln -s /root/icedtea-web-image/bin/javaws  /usr/bin/javaws_

Below is the run.conf file where we have defined the JVM parameters.
[run.txt](https://github.com/corretto/corretto-8/files/5508310/run.txt)

**Note**: We used 32-bit Oracle JDK to build our application and are trying to run it using 64-bit Amazon-Corretto-8 JDK in Linux OS. Previously we used to build it using 32-bit Oracle JDK and run it using 64-bit Oracle JRE.

**Comment by lutkerd** [comment]
What version of Oracle JDK are you migrating from?
Can you successfully run `keytool -keystore /var/AdventNet/WebNMS/conf/transport.key -list` using the keytool from Corretto8 and from Oracle?

There were some upstream changes in keyStore fallback and I want to rule that out. See https://bugs.openjdk.java.net/browse/JDK-8129988

**Comment by Yoshitha24** [comment]
Hi,

The version of Oracle JRE we use is 64-bit Linux 1.8.0_101. However for building our application we use a 32-bit Oracle JDK Linux 1.8.0_92.

We are able to successfully run the command : _keytool -keystore /var/AdventNet/WebNMS/conf/transport.key -list_ on both Oracle and Corretto installations. When prompted to enter the password, we have entered the password set by the application.

The following is the result in Corretto installation:
_Keystore type: jks
Keystore provider: SUN
Your keystore contains 1 entry_

The following is the result in Oracle installation:
_Keystore type: JKS
Keystore provider: SUN
Your keystore contains 1 entry_

We tried entering the wrong password with the above command and got the same error we were facing:
_java.io.IOException Keystore was tampered with, or password was incorrect._

We also tried executing "keytool -keystore cacerts -list" under _jre/lib/security_. We entered the password "_changeit_" during authentication and we are able to see the list.

**Comment by lutkerd** [comment]
The only way I've been able to reproduce that error is by actually specifying the wrong password. Can you generate a new testing keystore with the old Oracle JDK that was used to create yours and attach it here? Do the keystore and key use the same password? I am assuming yes or it would likely have a different exception.

**Comment by lutkerd** [comment]
Hi, Can you try this with the latest Oracle JDK and see if it also has the same problem?

**Comment by Yoshitha24** [comment]
Hi,

Please find the attached keystore file generated using Oracle 1.8.0_101.
[keystore.txt](https://github.com/corretto/corretto-8/files/5524049/keystore.txt)

We are using the **same password** for keystore and key.
We have tried running our application with the latest **Oracle JDK 8- JDK8u271**. We are able to see the same error:
_ERROR [Connector] Error starting connector.
java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
Caused by: java.security.UnrecoverableKeyException: Password verification failed_

We also tried out running the command : _keytool -keystore /var/AdventNet/WebNMS/conf/transport.key -list_ with latest Oracle JDK 8 and we are able to list the keys on entering the password set by the application. We are also able to open the cacerts file, but the following warning is displayed :
_<verisignclass2g2ca [jdk]> uses a 1024-bit RSA key which is considered a security risk. This key size will be disabled in a future update._

**Note**: In this link: https://www.oracle.com/java/technologies/javase/8all-relnotes.html#8u92-b31 we see that the default key size for keytool has changed from 1024 bits to 2048 bits in JDK8u151. Could this be the reason for the error?

**Comment by lutkerd** [comment]
Hello,
It may be the "Better keystore handling" in 8u151": https://www.oracle.com/java/technologies/javase/8all-relnotes.html#R180_151

Can you follow this procedure to regenerate your keystore?

```
Due to the more rigorous procedure of reading a keystore content, some keystores (particularly, those created with old versions of the JDK or with a JDK from other vendors) might need to be regenerated.

The following procedure can be used to import the keystore:

1. Before you start, create a backup of your keystore. For example, if your keystore file is /DIR/KEYSTORE, make a copy of it:

cp /DIR/KEYSTORE /DIR/KEYSTORE.BK

Download an older release of the JDK, prior CPU17_04, and install it in a separate location. For example: 6u161, 7u151, or 8u141. Suppose, that older JDK is installed in the directory /JDK8U141

2. Make sure that the keystore can be successfully read with the keytool from that older directory. For example, if the keystore file is located in /DIR/KEYSTORE, the following command should successfully list its content:

/JDK8U141/bin/keytool -list /DIR/KEYSTORE

3. Import the keystore. For example:

/JDK8U141/bin/keytool -importkeystore \
-srckeystore /DIR/KEYSTORE \
-srcstoretype JCEKS \
-srcstorepass PASSWORD \
-destkeystore /DIR/KEYSTORE.NEW \
-deststoretype JCEKS \
-deststorepass PASSWORD

4. Verify that the newly created keystore is correct. At the very least, make sure that the keystore can be read with keytool from a newer JDK:
/NEW_JDK/bin/keytool -list /DIR/KEYSTORE.NEW

After successful verification, replace the old keystore with the new one:
mv /DIR/KEYSTORE.NEW /DIR/KEYSTORE

Keep the backup copy of the keystore at least until you are sure the imported keystore is correct.

JDK-8181370 (not public)
```

**Comment by Yoshitha24** [comment]
Hi,

We have tried out the above procedure with JDK-1.8.0_101 as the Old JDK and JDK-8u271 as the new JDK. We are able to open backup keystore with Old JDK and new imported keystore with New JDK with the help of _"keytool -list"_ command.  However while running the services the problem still exists. 

From the link https://www.oracle.com/java/technologies/javase/8all-relnotes.html#8u92-b31 we see that:
#### New defaults for DSA keys in jarsigner and keytool (Changes in 8u151)
For DSA keys, the default signature algorithm for keytool and jarsigner has changed from **SHA1withDSA** to **SHA256withDSA** and the default key size for keytool has changed from **1024** bits to **2048** bits.

Could above be a possible suspect?

#### Disable JARs signed with DSA keys less than 1024 bits (Changes in 8u161)

DSA keys less than 1024 bits have been added to the jdk.jar.disabledAlgorithms Security property in the java.security file. This property contains a list of disabled algorithms and key sizes for signed JAR files. If a signed JAR file uses a disabled algorithm or key size less than the minimum length, signature verification operations will ignore the signature and treat the JAR as if it were unsigned. This can potentially occur in the following types of applications that use signed JAR files:

**1**. Applets or Web Start Applications
**2**.Standalone or Server Applications run with a SecurityManager enabled and that are configured with a policy file that grants permissions based on the code signer(s) of the JAR file.
Running jarsigner -verify -verbose on a JAR file signed with a weak algorithm or key will print more information about the disabled algorithm or key.

**Note**: Our application is applet based and we use java web start feature. Also our jars are signed during building of the application using jarsigner. For building we are using 32-bit Oracle JDK 1.8.0_92 and for running we got an error while testing with 8u271. It worked fine with JRE 1.8.0_101. Could using different jre and jdk in this case pose a problem?
transport.key uses the SHA1withDSA signature algorithm and a 1024-bit DSA key.

We are also using Secure Random with SHA1PRNG.

Thankyou

**Comment by lutkerd** [comment]
Based on the exception and reading the source code, it just seems like the password validation is failing and it is not related to jar signing or key signatures.

Are you able to run correctly if you keep the existing version of the OracleJDK and use the updated javaws from icedtea?
Can you run your app directly without JBoss or javaws using the latest Corretto and updated keystore?

You can run `java -XshowSettings:properties -Djavax.net.ssl.keyStorePassword=<your_pass> -version` to make sure your password is getting properly passed through to the jvm.

**Comment by Yoshitha24** [comment]
Hi,

We are able to run it using current Oracle version- JRE8u101 along with icedtea javaws.

It is not possible for us to run it without using JBoss as our application is dependent on it in various ways.
On running the command: _java -XshowSettings:properties -Djavax.net.ssl.keyStorePassword=<your_pass> -version_ , we can see that the password is correct and hence is properly passed through jvm.

We were not able to upgrade to latest Oracle JDK version which is 8u271, so we tried to see which is the latest compatable Oracle version for our application. We have seen that we were able to upgrade till 8u202. On trying the Oracle version **JDK-8u211**, we are facing the same error. We read that from 8u211, the licenses of Oracle JDKs are under Java SE OTN License and are updated with latest security patches.

**Note**: We have a script to create the keystore everytime we install the application.

Thankyou

**Comment by lutkerd** [comment]
What version of Java and keytool are you using to create the keystore at install time? Can you share the script or command(s) used?
I wasn't able to find any changes in the JDK between 8u202 and 8u212 that would cause the problem.

**Comment by Yoshitha24** [comment]
Hi,

I guess the script uses the keytool from the JDK we set in JAVA_HOME path.
Please find the script "_generate_keys.txt_" used to generate keys.
[generate_keys.txt](https://github.com/corretto/corretto-8/files/5565133/generate_keys.txt)

We have set the JVM property -Djava.security.debug=keystore to debug the issue. We can only find one additional comment from it : **_ERROR [STDERR] keystore: JavaKeyStore load: private key count: 0. trusted key count: 220_**
Please find the attached error_corretto.log for the whole stacktrace along with jvm parameters set.
[error_corretto.log](https://github.com/corretto/corretto-8/files/5565145/error_corretto.log)

As mentioned before, on running the command : _**keytool -keystore /var/AdventNet/WebNMS/conf/transport.key -list**_ on Oracle installation and on entering the password set by the application, the below is the result:
_Keystore type: JKS
Keystore provider: SUN
Your keystore contains 1 entry
<server-alias>, Nov 19, 2020, PrivateKeyEntry,
**Certificate fingerprint (SHA1)**: <***key***>_

But upon running the command _**keytool -v -list -alias <-server-alias-> -keystore <-keystore->**_ on the same installation, the result is:
Alias name:  <-server-alias->
Creation date: Nov 19, 2020
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: C=**, ST=**, L=**, O=**, OU=**, CN=**
Issuer: C=**, ST=**, L=**, O=**, OU=**, CN=**
Serial number: **
Valid from: Thu Nov 19 13:02:09 IST 2020 until: Sat Jul 29 13:02:09 IST 2034
Certificate fingerprints:
         MD5:  <-key->
         SHA1: <-key->
         SHA256: <-key->
Signature algorithm name: **SHA256withDSA**
Subject Public Key Algorithm: **2048-bit DSA key**
Version: 3

Extensions:

#1: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
<--->                                      ]]

 **Note**: We are using TLSv1.2 and SSLv3 protocols. I guess ssl-apache is using the SHA1 protocol.

Thanks

**Comment by lutkerd** [comment]
I believe the fingerprint is just a SHA-1 hash of the key itself while the signature algorithm is used to sign the public key certificate. So they should be different. I am not sure if JAVA_HOME has an effect on the keytool used, I would expect that to come from the PATH. I would like to be sure you are using the keytool that matches the new java executable you are ultimately running with.

Can you also try adding `-Djdk.security.allowNonCaAnchor=true`? this will allow for loading certificates that don't have a known root CA in the chain.

**Comment by davecurrie** [comment]
@Yoshitha24 Is there an update on this?
