### ISSUE TITLE
JVM crash since 8u282 in JNI code

### ISSUE THREAD

**Issue by tmoseneder** [corretto/corretto-8#312]
### Description
A JVM crash in some JNI code of Bonjour (the Apple MDNS implementation). I noticed it when trying to update to the newest Corretto version and was able to track down the faulty code and also the version in which it broke. The issue is 100% reproducable starts happening with 8.282.10.1 (it still occurs with 8u292). 

### To Reproduce
Here is a prebuilt JAR which demonstrates the issue. 
[bonjour.zip](https://github.com/corretto/corretto-8/files/6621703/bonjour.zip)
The code basically only initiates our self-built AiO java library (we had to fix an issue in the native code) for Bonjour (see: https://github.com/smartbow-gmbh/bonjour) and registers a example service in the network.

<details>

```
Path p = Files.createTempDirectory("libs");
DNSSDDllProvider.setDataDir(p);
try {
      DNSSD.register("testService", "_test._tcp.", 6789, new RegisterListener() {      
        @Override
        public void serviceRegistered(DNSSDRegistration registration, int flags, String serviceName, String regType, String domain) {
          System.out.println("registered");
          System.exit(0);
        }
      });
    } catch (DNSSDException e1) {
      e1.printStackTrace();
    }
```

</details>

### Expected behavior
The example should not crash 
### Screenshots
![correttoIssue](https://user-images.githubusercontent.com/42213013/121310063-3a972180-c903-11eb-9dac-62b01e1eb8c1.PNG)

### Platform information
OS: Windows 10
Version: I tested it with 272 (works), 275 (works), 282 (not working) and 292 (not working)

### Additional context
The crash file - I can also generate a .mdmp if needed. The log says it crashes in the BlockForData method (source for that can be found [here](https://opensource.apple.com/source/mDNSResponder/mDNSResponder-878.260.1/mDNSShared/Java/JNISupport.c.auto.html ))
[hs_err_pid20708.log](https://github.com/corretto/corretto-8/files/6621787/hs_err_pid20708.log)

**Comment by alvdavi** [comment]
Hi,

Thanks for your report.

I have been trying to check this issue, but I haven't been able to reproduce the issue as I get:
```
com.apple.dnssd.AppleDNSSDException: DNS-SD Error -65563: SERVICENOTRUNNING
        at com.apple.dnssd.AppleService.ThrowOnErr(DNSSD.java:616)
        at com.apple.dnssd.AppleRegistration.<init>(DNSSD.java:720)
        at com.apple.dnssd.AppleDNSSD._register(DNSSD.java:548)
        at com.apple.dnssd.DNSSD.register(DNSSD.java:242)
        at com.apple.dnssd.DNSSD.register(DNSSD.java:271)
        at at.tm.test.Main.main(Main.java:19)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
```

Usually a failure inside JNI points to a problem in the acual dll, however, there is one thing special that differentiates Corretto 275 from Corretto 282. In this version, we changed from building using Visual Studio 2010 to Visual Studio 2013. I have seen some JNI projects fail due to this, but it was always because they made the assumption that msvcr100.dll would be already loaded in the process memory (as it was a requirement for java) and now it was no longer the case (being replaced with msvcr120.dll). If there wasn't a copy of msvcr100.dll, that would cause a failure.

However, I've been digging through the jar you've sent us and I've verified that neither `dnssd.dll` nor `jdns_sd.dll` relies on msvcr100.dll, so I doubt this is the issue either.

AdoptOpenJDK binaries moved to VisualStudio2013 before 8u275. Could you test with the 8u275 and 8u282 of Adopt binaries? Depending of the results, we can draw some conclusions:

- Fails with 8u275 and 8u282: This means what causes the issue is most likely not a change in the jvm code but in the Visual Studio used to compile
- Works with 8u275, but fails with 8u282: We can disregard the compiler change, there is a change in the JDK source code between these versions
- Works with 8u275 and 8u282: This makes the issue a Corretto specific problem, narrowing down where we need to look
- Fails with 8u275, works with 8u282: Not really expecting this to happen, honestly

**Comment by tmoseneder** [comment]
Thanks for your reply and the insights regarding the msvcr100.dll issue, things like that are always good to know!

Sorry, seems like I forgot the fact that literally no one has Bonjour installed or even knows about it (a fact that makes troubleshooting it quite hard). This error basically just means that the library could not find a running Bonjour service because you most certainly don't have Bonjour installed on your system. In order to get it installed you would usually install Apple iTunes (the official way). There are also places where you can find a standalone installer for it (which isn't quite an official way). 

In case you want to actually reproduce it you would have to install Bonjour - I could maybe provide you a standalone installer if needed.

I have tested it with quite a few Adopt versions now (282, 275, 272, 242, 222, 212, 202) and it seems like it broke going from 8u202 to 8u212. I couldn't find any hint in the release notes when the switch happened for them though. 
Oracle JDK crashes from 8u261 upwards - looking through the release notes I found that they did go from VS2010 to VS2017 in that version ([see the "New Features" section from 8u261](https://www.oracle.com/java/technologies/javase/8all-relnotes.html)) so it looks like you are onto something there.
