### ISSUE TITLE
ByteArrays ClassNotFound

### ISSUE THREAD

**Issue by RickMu** [corretto/corretto-8#355]
### Describe the bug
This might be a newbie question, but 
After this [change](https://github.com/corretto/corretto-8/commit/dc4738291f390cc3c418ca7a597cf794e6a99736)

My jar keeps complaining  about ByteArrays class not found error. 
```
at sun.security.ssl.RandomCookie.isT11Downgrade(RandomCookie.java:139) ~[?:1.8.0_312]
    at sun.security.ssl.RandomCookie.isVersionDowngrade(RandomCookie.java:127) ~[?:1.8.0_312]
    at sun.security.ssl.ServerHello$ServerHelloConsumer.onServerHello(ServerHello.java:959) ~[?:1.8.0_312]
    at sun.security.ssl.ServerHello$ServerHelloConsumer.consume(ServerHello.java:869) ~[?:1.8.0_312]
....
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
....
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_292]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_292]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

```

And when I look at the stacktrace I see jar starts Thread with java version `1.8.0_292`, but then somehow
references classes from `1.8.0_312`

The link I sent above essentially shows that the `ByteArrays` class has been removed in newer version.

My java version is 1.8.0_312, but I guess my jar file was compiled earlier and is on 1.8.0_292. However I still expect Java to be backwards compatible ? 

Is there something I'm missing, if so what's likely the cause and what is the correct way out of this situation ?

### Expected behavior
Expect a newer version of java can still run an older version of jar

**Comment by mrserb** [comment]
Hi, thank you for your report.

I checked the commit which you provided - the ByteArrays class was actually [added](https://github.com/corretto/corretto-8/commit/dc4738291f390cc3c418ca7a597cf794e6a99736#diff-a1962448ebcf5818ce3c28c24ae280d52d29683a0cbcef8eaa60a7a415f4d800). Can you please provide a standalone example to reproduce this issue?

**Comment by navyxliu** [comment]
Hi, @RickMu , 

I have seen a similar issue in the internal use of JDK8. 

Quite the opposite. sun.security.util.ByteArrays is added to jdk8u312. it's very likely that you intermix rt.jar from one jdk and jsse.jar from the other jdk.  it's called jar hell. 

RandomCookie from 8u312 jsse.jar refers to ByteArrays which is in rt.jar of 8u312. however, it can't find the class from your 8u292's rt.jar. 

You need to check your classpath.  make sure that both rt.jar and jsse.jar come from a single jdk or jre. 
a command `-verbose:class` will dump all class loading information.
