### ISSUE TITLE
Problems with WildFly 9 after Update from 322 to 332 (only Windows)

### ISSUE THREAD

**Issue by DevMaddin** [corretto/corretto-8#383]
### Describe the bug
After Update from 8.322 to 8.332 i started my WildFly and it deployed without errors. But when i open my webapp i got this exceptions:
```
10:21:41,962 ERROR [io.undertow.request] (default task-2) UT005023: Exception handling request to /opusp/: javax.servlet.ServletException: java.io.IOError: java.io.FileNotFoundException: Invalid file path
        at org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:848)
        at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:777)
        at org.apache.jsp.index_jsp._jspService(index_jsp.java:63)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:69)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:366)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:326)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:259)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:86)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.jsp.JspFileHandler.handleRequest(JspFileHandler.java:32)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:51)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:56)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:72)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:282)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:261)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:80)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:172)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:774)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOError: java.io.FileNotFoundException: Invalid file path
        at org.xnio.channels.Channels$4.run(Channels.java:998)
        at org.xnio.channels.Channels$4.run(Channels.java:988)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.xnio.channels.Channels.<clinit>(Channels.java:988)
        at io.undertow.servlet.spec.ServletOutputStreamImpl.close(ServletOutputStreamImpl.java:609)
        at io.undertow.servlet.spec.HttpServletResponseImpl.closeStreamAndWriter(HttpServletResponseImpl.java:467)
        at io.undertow.servlet.spec.HttpServletResponseImpl.responseDone(HttpServletResponseImpl.java:551)
        at io.undertow.servlet.spec.HttpServletResponseImpl.sendRedirect(HttpServletResponseImpl.java:194)
        at org.apache.jsp.index_jsp._jspService(index_jsp.java:56)
        ... 35 more
Caused by: java.io.FileNotFoundException: Invalid file path
        at java.io.FileOutputStream.<init>(FileOutputStream.java:206)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
        at org.xnio.channels.Channels$4.run(Channels.java:993)
        ... 43 more
```

### To Reproduce
WildFly with a war. Loads the page with 8.322. After Update above error.

### Expected behavior
Load the Servlet/WepApp.

### Screenshots
---

### Platform information
    OS: Windows 10 (20H2)
    Version 1.8.0_332-b08

### Additional context
---

Other thing: The Link in the Change-Log -> https://github.com/openjdk/jdk8u/releases/tag/jdk8u332-b08 does not exist. The last Tag is b06.

**Comment by alvdavi** [comment]
Hi,

Thank you for reporting this issue. The new release includes an extra check on Windows systems to validate paths. This is done to detect some problematic paths that were being accepted before and truncated when interacting with the file system, which could lead to unexpected behavior. This check can cause issues when using paths that start with `\\?\`.

For this scenarios, this extra check can be disabled by passing the system property `-Djdk.io.File.enableADS`.

Could you please let us know if your application is working with this workaround?

Do you know exactly which file path was being processed by your application at that moment? Any chance it was a file path that starts with `\\?\`?

Thanks,

David

**Comment by olivergillespie** [comment]
> The Link in the Change-Log -> https://github.com/openjdk/jdk8u/releases/tag/jdk8u332-b08 does not exist. The last Tag is b06.

Thanks for pointing this out. We expect that tag to be created in the upstream openjdk repository some time in the near future.

**Comment by DevMaddin** [comment]
> 

When i add the following line in the _**standalone.conf.bat**_ it works! 👍

`set "JAVA_OPTS=%JAVA_OPTS% -Djdk.io.File.enableADS`

Is this necessary for us (WildFly-User) or an issue that will be corrected in a future version?

**Comment by olivergillespie** [comment]
Great, thanks for confirming.

I don't know for sure but I suspect this might be fixed in a future version, or could be fixed in the triggering library itself. I believe [this line](https://github.com/xnio/xnio/blob/3.x/api/src/main/java/org/xnio/channels/Channels.java#L1098) in the `xnio` library is triggering the issue due to the trailing colon in the file path, but I'm not certain yet whether that should be considered a valid path or not.

**Comment by DevMaddin** [comment]
I have tested an update on a Linux-System and there was no problem!

What is "enableADS" exactly? I can´t find it. 🤷‍♂️

**Comment by alvdavi** [comment]
ADS stands for Alternate Data Streams, a feature of NTFS:
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/c54dec26-1551-4d3a-a0ea-4fa40f848eb3

The reason you can't find any reference to the `jdk.io.File.enableADS` system property is because it was added in this release. As part of the defense in depth for the JDK, a change to limit the usage of colon in filenames in Windows was added, as this could lead to unexpected behavior. Although rarely used, Alternate Data Streams do make use of a colon in the filename, so the `jdk.io.File.enableADS` system property was added to disable this new check.

**Comment by mrserb** [comment]
I think it is related to the issue: https://bugs.openjdk.java.net/browse/JDK-8285445 will be fixed in the next upcoming version.

**Comment by DevMaddin** [comment]
Good morning.

Thanks to @alvdavi for explanation!
Thanks to  @mrserb for information!

I will close the issue when the next update works!

Best regards and have a nice start into the week. 😊

**Comment by DevMaddin** [comment]
After Update to 8.342 we don´t need the Java-Option. 👍

I close the issue.
