### ISSUE TITLE
Request to merge the fix for JDK-8247907

### ISSUE THREAD

**Issue by MushyMiddle** [corretto/corretto-8#389]
### Describe the bug
Hi.  [JDK-8247907](https://bugs.openjdk.java.net/browse/JDK-8247907) was introduced into Corretto after 1.8.0_265.  Thus, we're stuck at that release until this fix is pulled into Corretto 8.  Can this be scheduled into an upcoming release of Corretto 8?  It has been merged into at least Corretto 16, I believe.

### To Reproduce
See [JDK-8247907](https://bugs.openjdk.java.net/browse/JDK-8247907).

### Expected behavior
No crashes such as:

`Caused by: java.lang.IllegalArgumentException: can't parse argument number:`
`at java.text.MessageFormat.makeFormat(MessageFormat.java:1429)`
`at java.text.MessageFormat.applyPattern(MessageFormat.java:479)`
`at java.text.MessageFormat.<init>(MessageFormat.java:362)`
`at java.text.MessageFormat.format(MessageFormat.java:840)`
`at org.slf4j.bridge.SLF4JBridgeHandler.getMessageI18N(SLF4JBridgeHandler.java:251)`
`at org.slf4j.bridge.SLF4JBridgeHandler.callLocationAwareLogger(SLF4JBridgeHandler.java:209)`
`at org.slf4j.bridge.SLF4JBridgeHandler.publish(SLF4JBridgeHandler.java:285)`
`at java.util.logging.Logger.log(Logger.java:738)`
`at java.util.logging.Logger.doLog(Logger.java:765)`
`at java.util.logging.Logger.log(Logger.java:851)`
`at com.sun.org.slf4j.internal.Logger.debug(Logger.java:53)`

### Screenshots
N/A

### Platform information
    OS: Ubuntu 18.04 LTS/20.04 LTS
    Version: any *after* build 1.8.0_265-b01

### Additional context
Logging is coming from 3rd-party libs, e.g. CXF, so code is out of our control.  It's also worth mentioning that internal classes are affected, e.g. org.jcp.xml.dsig.internal.dom.DOMReference.java, so this issue isn't limited to 3rd-party libs or application code.

**Comment by vsg** [comment]
To clarify on this issue, **XML digital signatures do not work in Corretto 8.** 

The last version of Corretto 8 in which this feature still works is 1.8.0_265. After that release, there was a change of logging style in org/jcp/xml/dsig/internal/dom/DOMReference.java from:
`LOG.debug("Reference object uri = " + uri);`
to
`LOG.debug("Reference object uri = {}", uri);`

The issue is caused by a buggy implementation of the "LOG" (com/sun/org/slf4j/internal/Logger.java), which just passes the log message and parameters to JUL logger, without any changes. But the problem is that while "{}" is the expected parameter substitution syntax for SLF4J, the JUL expects "{0}" instead. This causes the `java.lang.IllegalArgumentException: can't parse argument number` error, and makes some features of XML digital signatures unusable.

The com/sun/org/slf4j/internal/Logger.java was fixed in future Java and Corretto versions. The request is to backport this change to Corretto 8.

**Comment by caojoshua** [comment]
I've submitted a PR for openjdk11: https://github.com/openjdk/jdk11u-dev/pull/1129.

The backport does not apply to openjdk8, and will need some rewriting. The patch uses [StackWalker API](https://docs.oracle.com/javase/9/docs/api/java/lang/StackWalker.html), which only exists in Java >= 9. We are tracking this work internally.

**Comment by navyxliu** [comment]
[JDK-8247907](https://bugs.openjdk.java.net/browse/JDK-8247907) hasn't been backported to jdk8u. Why does this bug affect Corretto after 1.8.0_265?

**Comment by MushyMiddle** [comment]
> [JDK-8247907](https://bugs.openjdk.java.net/browse/JDK-8247907) hasn't been backported to jdk8u. Why does this bug affect Corretto after 1.8.0_265?

See post above by @vsg for specifics.

**Comment by caojoshua** [comment]
Closing this as won't fix. This bug has little impact. The backport the Corretto-8 would is non-trivial and requires a rewrite using new APIs. As a solution, we recommend upgrading to Corretto-17 where the bug is not present.

@MushyMiddle please let us know if there are any concerns.

**Comment by MushyMiddle** [comment]
@caojoshua I'm sure it has little impact to you, however for us, we cannot run with this bug in place, largely due to third-party libraries (e.g. Apache CXF) that are affected by this bug, not to mention the runtime itself - see stack puke above, and comments from @vsg .

And, upgrading 2M+ lines of Java plus tons of third-party libs to Java 17.  That has lots of impact.  Just not on you.

Thanks, Team.  Glad you have our back.  I guess "LTS" doesn't really mean that much to you.  It's 2023 - not 2026.

See https://aws.amazon.com/corretto/faqs/#support.

**Comment by benty-amzn** [comment]
Re-opening this. 

It looks like the regression was introduced into jdk8u272 by [JDK-8177334](https://bugs.openjdk.org/browse/JDK-8177334).
We've added a comment noting the regression on [JDK-8247907](https://bugs.openjdk.org/browse/JDK-8247907) and will discuss appropriate action with the openjdk project.

The fix for JDK11+ makes use of the `StackWalker` API, introduced in JDK9. Since this API is not available in corretto-8, the fix would have to be rewritten, and there is no direct equivalent available. The risk of introducing a new bug which potentially impacts other users has to be balanced against the impact of this regression. We'll update this issue as we determine next steps.
