### ISSUE TITLE
javax.net.ssl.SSLException: Tag mismatch while HTTPS calls

### ISSUE THREAD

**Issue by jcarnus** [corretto/corretto-8#424]
Hi,
Using the latest Amazon Correto [8.342.07.4] (https://github.com/corretto/corretto-8/releases/tag/8.342.07.4), we are seeing this exception when reaching HTTPS endpoint when the link beetween the 2 services is gigabit. The issue seems to not appears when bitrate is so much lower.

This seems similar to this bug : https://bugs.openjdk.org/browse/JDK-8277970

Exception:
Caused by: javax.net.ssl.SSLException: Tag mismatch!
	at sun.security.ssl.Alert.createSSLException(Alert.java:133) ~[?:1.8.0_342]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:324) ~[?:1.8.0_342]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:267) ~[?:1.8.0_342]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:262) ~[?:1.8.0_342]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:119) ~[?:1.8.0_342]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1400) ~[?:1.8.0_342]
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1368) ~[?:1.8.0_342]
	at sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:73) ~[?:1.8.0_342]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:962) ~[?:1.8.0_342]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_342]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1.8.0_342]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_342]
	at sun.net.www.MeteredStream.read(MeteredStream.java:134) ~[?:1.8.0_342]
	at java.io.FilterInputStream.read(FilterInputStream.java:133) ~[?:1.8.0_342]
......
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
	at com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:620) ~[sunjce_provider.jar:1.8.0_342]
	at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1116) ~[sunjce_provider.jar:1.8.0_342]
	at com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1053) ~[sunjce_provider.jar:1.8.0_342]
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:941) ~[sunjce_provider.jar:1.8.0_342]
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491) ~[sunjce_provider.jar:1.8.0_342]
	at javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:779) ~[?:1.8.0_342]
	at javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730) ~[?:1.8.0_342]
	at javax.crypto.Cipher.doFinal(Cipher.java:2463) ~[?:1.8.0_342]

**Comment by eastig** [comment]
Hi @jcarnus,
Thank you for reporting the issue.

According to https://bugs.openjdk.org/browse/JDK-8277970, it affects java 17, 18 and 20 but not 8 on which corretto 8 is based on.

I found bug reports possibly related to the issue:
https://bugs.openjdk.org/browse/JDK-8280158
https://bugs.openjdk.org/browse/JDK-8212096

Had you had the issue on Amazon Correto before the latest release 8.342.07.4?
Do you have the issue on other distributions of OpenJDK 8?

**Comment by jcarnus** [comment]
Thanks, in our case, the bug appears while starting calling HTTPS Service between 2 servers in 10gbit, making line 800mb/s of real speed of download. And the bug is really intermittent.

I also have open a bug in Oracle side : http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8293973
