### ISSUE TITLE
Make Corretto work with webkit if user build it with OracleJDK.

### ISSUE THREAD

**Issue by yoroto** [corretto/corretto-8#48]
### Is your feature request related to a problem?
Corretto at the moment does not release with webkit and a few other JFX binaries. However, if user decided to build Corretto with OracleJDK, the artifacts would include those binaries. There is an issue reported by one of the users that even in that case, webkit project does not work. We need to figure out the root cause of it.

The user issue reported on StackOverflow: https://stackoverflow.com/questions/54123188/unsatisfiedlinkerror-occurs-on-openjfx-webkit-32bit

### Describe a solution you would like
Make sure Corretto would work with webkit if user decide to build Corretto themselves.

### Describe alternatives you have considered
N/A

### Additional context
https://stackoverflow.com/questions/54123188/unsatisfiedlinkerror-occurs-on-openjfx-webkit-32bit

**Comment by davecurrie** [comment]
This is a bit of an extreme edge case and not likely to make the roadmap, so closing this issue.

**Comment by asirihewage** [comment]
```
Fri Aug 19 14:52:28 IST 2022 Thread[GITST Extractor,5,main] java.lang.ClassNotFoundException: MyApp
----------------------------------------------------------------
Fri Aug 19 14:52:29 IST 2022:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance a816c00e-0182-b569-3ba1-00000ea97e60
on database directory C:\Users\Asiri Hewage\gitst_crawlr_db with class loader sun.misc.Launcher$AppClassLoader@33909752 
Loaded from file:/E:/Data%20Miner/GITSTWebCrawler.jar
java.vendor=Amazon.com Inc.
java.runtime.version=1.8.0_342-b07
user.dir=E:\Data Miner
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=null
derby.stream.error.field=MyApp.DEV_NULL
Database Class Loader started - derby.database.classpath=''
Exception in thread "JavaFX Application Thread" java.lang.UnsatisfiedLinkError: C:\Program Files\Amazon Corretto\jdk1.8.0_342\jre\bin\jfxwebkit.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
        at java.lang.Runtime.load0(Runtime.java:810)
        at java.lang.System.load(System.java:1088)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryFullPath(NativeLibLoader.java:201)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:94)
        at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:39)
        at com.sun.webkit.WebPage.lambda$static$0(WebPage.java:133)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.webkit.WebPage.<clinit>(WebPage.java:132)
        at javafx.scene.web.WebEngine.<init>(WebEngine.java:881)
        at javafx.scene.web.WebEngine.<init>(WebEngine.java:868)
        at javafx.scene.web.WebView.<init>(WebView.java:273)
        at main.crawler.CrawlerSwingBrowser$1.run(CrawlerSwingBrowser.java:49)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
        at java.lang.Thread.run(Thread.java:750)
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: Could not initialize class com.sun.webkit.WebPage
        at javafx.scene.web.WebEngine.<init>(WebEngine.java:881)
        at javafx.scene.web.WebEngine.<init>(WebEngine.java:868)
        at javafx.scene.web.WebView.<init>(WebView.java:273)
        at main.crawler.CrawlerSwingBrowser$1.run(CrawlerSwingBrowser.java:49)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
        at java.lang.Thread.run(Thread.java:750)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at main.crawler.CrawlerSwingBrowser$3.run(CrawlerSwingBrowser.java:81)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
        at java.lang.Thread.run(Thread.java:750)
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: Could not initialize class com.sun.webkit.WebPage
        at javafx.scene.web.WebEngine.<init>(WebEngine.java:881)
        at javafx.scene.web.WebEngine.<init>(WebEngine.java:868)
        at javafx.scene.web.WebView.<init>(WebView.java:273)
        at main.crawler.CrawlerSwingBrowser$1.run(CrawlerSwingBrowser.java:49)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
        at java.lang.Thread.run(Thread.java:750)
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: Could not initialize class com.sun.webkit.WebPage
        at javafx.scene.web.WebEngine.<init>(WebEngine.java:881)
        at javafx.scene.web.WebEngine.<init>(WebEngine.java:868)
        at javafx.scene.web.WebView.<init>(WebView.java:273)
        at main.crawler.CrawlerSwingBrowser$1.run(CrawlerSwingBrowser.java:49)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
        at java.lang.Thread.run(Thread.java:750)
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: Could not initialize class com.sun.webkit.WebPage
        at javafx.scene.web.WebEngine.<init>(WebEngine.java:881)
        at javafx.scene.web.WebEngine.<init>(WebEngine.java:868)
        at javafx.scene.web.WebView.<init>(WebView.java:273)
        at main.crawler.CrawlerSwingBrowser$1.run(CrawlerSwingBrowser.java:49)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
        at java.lang.Thread.run(Thread.java:750)
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: Could not initialize class com.sun.webkit.WebPage
        at javafx.scene.web.WebEngine.<init>(WebEngine.java:881)
        at javafx.scene.web.WebEngine.<init>(WebEngine.java:868)
        at javafx.scene.web.WebView.<init>(WebView.java:273)
        at main.crawler.CrawlerSwingBrowser$1.run(CrawlerSwingBrowser.java:49)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
        at java.lang.Thread.run(Thread.java:750)
```

**Comment by jianlinshi** [comment]
still an issue. any fixes?
